name: Solar Automation CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run CI test
        run: python raspberry_pi_code/test_automation_ci.py

      - name: Upload data logs
        uses: actions/upload-artifact@v4
        with:
          name: sensor-data
          path: data/
